### ISSUE TITLE
Installation in Senaite 1.x

### ISSUE THREAD

**Issue by yofori** [senaite/senaite.queue#13]
## Steps to reproduce
added senaite.queue to eggs section under [Instance]

## Current behavior
Download error on http://download.zope.org/ppix/: hostname 'download.zope.org' doesn't match 'vm06.plyp.com' -- Some packages may not be found!
Download error on http://download.zope.org/distribution/: hostname 'download.zope.org' doesn't match 'vm06.plyp.com' -- Some packages may not be found!
Couldn't find index page for 'senaite.queue' (maybe misspelled?)
Getting distribution for 'senaite.queue'.
Couldn't find index page for 'senaite.queue' (maybe misspelled?)
While:
  Installing instance.
  Getting distribution for 'senaite.queue'.
Error: Couldn't find a distribution for 'senaite.queue'.

## Expected behavior
senaite queue installed

**Comment by ramonski** [comment]
Should be released nowadays:
https://pypi.org/project/senaite.queue/

**Comment by eyahlin** [comment]
I'm using 1.3.4, and I got the same error as @yofori . I tried installing it manually using ```pip install senaite.queue```, and got this:

```ERROR: Could not find a version that satisfies the requirement pyphen==0.11.0 (from senaite.impress==2.2.0->senaite.lims>=1.3.0->senaite.queue==1.0.1) (from versions: 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0)```
```ERROR: No matching distribution found for pyphen==0.11.0 (from senaite.impress==2.2.0->senaite.lims>=1.3.0->senaite.queue==1.0.1)```

Is there a version of it that's compatible with Python 2.7?

**Comment by ramonski** [comment]
Hi @eyahlin,

you can not install `senaite.queue` via `pip`, but have to use `zc.buildout`: http://www.buildout.org/en/latest/

Using buildout, it will install `pyphen==0.11.0` without problem and it is also compatible with Python 2.7

See here for an example buildout.cfg:
https://github.com/senaite/senaite.core/blob/2.x/buildout.cfg

**Comment by eyahlin** [comment]
Hi @ramonski,

Unfortunately, I couldn't install it using buildout. I followed the instructions in the [user guide](https://senaitequeue.readthedocs.io/en/latest/installation.html). After running buildout,  I got the exact same issue and error message as @yofori .

I am using Senaite version 1.3.4. 

What other possible causes could there be for this?

**Comment by ramonski** [comment]
Please post your question on https://community.senaite.org
You need to probably just pin `senaite.lims` to a version < 2
